### PR TITLE
Adds instructions for running on save in phpstorm

### PR DESCRIPTION
**Pull request by 5outh**
I managed to get this working this morning so I thought I'd pass along my experience. I didn't really want to have to press a key combo in order to format, I just wanted it to happen when I saved, so I figured it out.

The image in the .md file is pointing at a location that does not yet exist, but will as soon as this is merged (s/5outh/phpfmt in the link). I thought that would be desired behavior.

Let me know if you want anything changed, and thanks for the excellent tool!

### CODE REVIEW

**Comment by 5outh** [comment]
Ah, nevermind. This is buggy, so I wouldn't recommend it after all :\

**Comment by Shaked** [comment]
Hey @5outh, have you checked https://github.com/phpfmt/phpstorm-phpfmt?

**Comment by 5outh** [comment]
No, thank you!

**Comment by Shaked** [comment]
It is in the README but maybe we can update it so that the beta will become official, @ccirello ?

**Comment by ccirello** [comment]
@Shaked make it so, please

**Pull request closed without merging**
