### PR TITLE
Fixed notice "Undefined variable: touchedFunction ..."

### PR DESCRIPTION
**Pull request by akalongman**
Fixed notice "Undefined variable: touchedFunction ...". Fixed issue #121

### CODE REVIEW

**Comment by ccirello** [comment]
Please, add a test to prove the bug.

**Comment by akalongman** [comment]
Test? Hmm, ok, maybe later, when I get a time for that.. But look at code, variable $touchedFunction might be not initialized in some cases.

**Comment by ccirello** [comment]
I see. That's why I want the test, to prove an execution path in which leads to unknown variable error.

**Comment by ccirello** [comment]
Merging manually so I can add tests.

**Pull request closed without merging**
